import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';
import { NegotiationAnalysisSchema } from './negotiation-response.dto';
import {
  CrossProfileInconsistencySchema,
  TimelineEntrySchema,
} from './profile-digest.dto';

export const FixSchema = z.object({
  summary: z.string(),
  steps: z.array(z.string()).min(1).max(5),
  example: z
    .object({
      before: z.string(),
      after: z.string(),
    })
    .nullable(),
  project_idea: z
    .object({
      name: z.string(),
      description: z.string(),
      endpoints: z.array(z.string()),
      bonus: z.string().nullable(),
      proves: z.string(),
    })
    .nullable(),
  time_required: z.string(),
});

// Issue without fix — used in the hot pass; fix is filled in from deep pass
// at merge time.
export const IssueHotSchema = z.object({
  // Stable per-issue key (concurrency-audit rule R2). Assigned deterministically
  // in the hot pass (slug of scope + hash of `what`), NOT generated by Claude.
  // Per-fix generation and storage key off this — never off array position.
  // Optional for back-compat: analyses stored before the split lack it.
  id: z.string().optional(),
  severity: z.enum(['critical', 'major', 'minor']).catch('minor'),
  category: z
    .enum([
      'keywords',
      'impact',
      'seniority',
      'stack',
      'format',
      'tone',
      'consistency',
    ])
    .catch('format'),
  what: z.string(),
  why: z.string(),
});

// Full Issue (hot + fix). Used in the merged AnalyzeResponse.
export const IssueSchema = IssueHotSchema.extend({
  fix: FixSchema,
});

// Claude sometimes returns a string instead of an array — coerce gracefully
const strOrArr = z
  .union([z.array(z.string()), z.string()])
  .transform((v) => (Array.isArray(v) ? v : [v]));

const techItemSchema = z.union([
  z.string(),
  z.object({ name: z.string(), category: z.string(), reason: z.string() }),
]);

export const ProjectRecommendationSchema = z.object({
  name: z.string(),
  description: z.string(),
  technologies: z.union([z.array(techItemSchema), z.string()]).transform((v) =>
    Array.isArray(v) ? v : [v],
  ),
  key_features: strOrArr,
  architecture: z.string(),
  advanced_concepts: strOrArr.optional(),
  success_criteria: strOrArr,
  difficulty_level: z.enum(['Beginner', 'Intermediate', 'Advanced', 'Expert']),
  why_it_matters: z.string(),
  what_matters: strOrArr.optional(),
  cv_bullet: z.string().optional(),
  signal_boost: z.string().optional(),
  architecture_diagram: z.string().nullable().optional(),
  sections: z.array(z.object({
    title: z.string(),
    duration: z.string(),
    steps: z.array(z.object({ title: z.string(), description: z.string() })),
  })).optional(),
  /** Backward compat — flat steps from analyses before sections were introduced */
  steps: z.array(z.object({ title: z.string(), description: z.string(), duration: z.string() })).optional(),
  edge_cases: z.array(z.object({ problem: z.string(), solution: z.string() })).optional(),
  going_further: z.array(z.string()).optional(),
  how_to_sell: z.object({
    github_readme_tip: z.string(),
    interview_pitch: z.string(),
    star_tactics: z.string(),
  }).optional(),
  interview_questions: z.array(z.object({ question: z.string(), answer: z.string() })).optional(),
  testing_strategy: z.string().nullable().optional(),
  gap_bridges: z.array(z.object({
    skill_name: z.string(),
    phase_title: z.string(),
    claim: z.string(),
  })).optional(),
});

export const ChallengeAnalysisSchema = z.object({
  status: z.enum(['cta', 'analyzed']),
  matched_language: z
    .enum(['typescript', 'python', 'java'])
    .nullable()
    .optional(),
  cta: z
    .object({
      language: z.string(),
      message: z.string(),
    })
    .nullable()
    .optional(),
  summary: z.string().nullable().optional(),
  strengths: z.array(z.string()).nullable().optional(),
  bridge_to_project: z.string().nullable().optional(),
});

export const TechnicalSkillSchema = z.object({
  name: z.string(),
  expected: z.number().min(0).max(10),
  current: z.number().min(0).max(10),
  evidence: z.string(),
});

export const TechnicalAnalysisSchema = z.object({
  reasoning: z.string(),
  skill_priority: z.array(z.string()).default([]),
  skills: z.array(TechnicalSkillSchema).length(5),
  recommendation: z.string(),
  // Optional for backward compat with analyses stored before this field
  // was removed from the tool schema.
  market_context: z.string().optional(),
  seniority_signals: z.array(z.string()),
});

// Claude sometimes returns plain strings instead of { term, tooltip } objects.
// Coerce strings to { term, tooltip: "" } so the analysis never crashes.
const HighlightTermEntrySchema = z
  .union([
    z.object({ term: z.string(), tooltip: z.string() }),
    z.string().transform((s) => ({ term: s, tooltip: '' })),
  ])
  .transform((v) => (typeof v === 'string' ? { term: v, tooltip: '' } : v));

// Reusable per-source schema (cv / linkedin)
const HighlightSourceSchema = z.object({
  flags:   z.array(HighlightTermEntrySchema).catch([]),
  issues:  z.array(HighlightTermEntrySchema).catch([]),
  skills:  z.array(z.string()).catch([]),
  weak:    z.array(HighlightTermEntrySchema).catch([]),
  metrics: z.array(HighlightTermEntrySchema).catch([]),
});

// Cover letter omits skills
const CoverLetterHighlightSchema = z.object({
  flags:  z.array(HighlightTermEntrySchema).catch([]),
  issues: z.array(HighlightTermEntrySchema).catch([]),
  weak:   z.array(HighlightTermEntrySchema).catch([]),
});

export const HighlightTermsSchema = z.object({
  // New per-source format
  cv:           HighlightSourceSchema.optional(),
  linkedin:     HighlightSourceSchema.optional(),
  cover_letter: CoverLetterHighlightSchema.optional(),
  // Flat format — kept for backward compat with old DB rows
  flags:  z.array(HighlightTermEntrySchema).catch([]).optional(),
  issues: z.array(HighlightTermEntrySchema).catch([]).optional(),
  skills: z.array(z.string()).catch([]).optional(),
  weak:   z.array(HighlightTermEntrySchema).catch([]).optional(),
});

export const AtsCriticalMissingKeywordSchema = z.object({
  keyword: z.string(),
  jd_frequency: z.number(),
  required: z.boolean(),
  sections_missing: z.array(z.string()),
  score_impact: z.number(),
  // Paste-ready truthful insertion (tool requires it; optional here so
  // pre-densification rows without it still replay).
  insertion: z
    .object({
      before: z.string().nullable(),
      after: z.string(),
    })
    .optional(),
});

// Bullet-by-bullet CV review (single-pass tool). `rewrite` is the premium
// half — the shaper nulls it out for free users.
export const BulletReviewSchema = z.object({
  original: z.string(),
  section: z.string(),
  verdict: z.enum(['strong', 'weak', 'fatal']).catch('weak'),
  flags: z
    .array(
      z.enum([
        'weak_verb',
        'no_metric',
        'passive_voice',
        'vague_scope',
        'buzzword',
        'no_outcome',
        'too_long',
      ]),
    )
    .catch([]),
  why: z.string(),
  rewrite: z.string().nullable(),
});

export const BulletReviewsSchema = z.object({
  bullets: z.array(BulletReviewSchema),
});

// Counts of premium content hidden by the shaper for free users — drives the
// upsell CTAs without leaking the content itself.
export const PremiumLockedSchema = z.object({
  fixes: z.number(),
  bullet_rewrites: z.number(),
  ats_keywords: z.number(),
  project: z.boolean(),
});

const JobDetailsSchema = z.object({
  title: z.string(),
  company: z.string(),
  seniority: z
    .enum([
      'junior',
      'junior-mid',
      'mid',
      'mid-senior',
      'senior',
      'not-mentioned',
    ])
    .nullable()
    .default('not-mentioned'),
  pay: z.string().nullable().default(null),
  office_location: z.string().nullable().default(null),
  work_setting: z
    .enum(['full-remote', 'on-site', 'hybrid', 'not-mentioned'])
    .nullable()
    .default('not-mentioned'),
  contract_type: z
    .enum([
      'CDI',
      'CDD',
      'freelance',
      'internship',
      'apprenticeship',
      'not-mentioned',
    ])
    .nullable()
    .default('not-mentioned'),
  languages_required: z
    .enum(['french-only', 'english-only', 'bilingual', 'not-mentioned'])
    .nullable()
    .default('not-mentioned'),
  years_of_experience: z.string().nullable().default(null),
  company_stage: z
    .enum(['startup', 'scale-up', 'sme', 'enterprise', 'not-mentioned'])
    .nullable()
    .default('not-mentioned'),
  jd_language: z.string().default('en'),
});

const AuditJdMatchSchema = z.object({
  required_skills: z.array(
    z.object({
      skill: z.string(),
      found: z.boolean(),
      // Optional for back-compat: rows stored before P1 lack it.
      match_strength: z.enum(['exact', 'partial', 'missing']).optional(),
      evidence: z.string().nullable(),
    }),
  ),
  experience_gap: z.string().nullable(),
});

// =============================================================================
// HOT pass schema — first response sent to the frontend (analysis_done event).
// Contains scores, audits without fixes, red flag titles, etc.
// =============================================================================

export const HotAnalyzeResponseSchema = z.object({
  score: z.number().min(0).max(100),
  verdict: z.enum(['Low', 'Medium', 'High']),
  confidence: z.object({
    score: z.number().min(0).max(100),
    reason: z.string(),
  }),
  breakdown: z.object({
    keyword_match: z.number().min(0).max(100),
    tech_stack_fit: z.number().min(0).max(100),
    experience_level: z.number().min(0).max(100),
    github_signal: z.number().min(0).max(100).nullable(),
    linkedin_signal: z.number().min(0).max(100).nullable(),
  }),
  ats_simulation: z.object({
    would_pass: z.boolean(),
    score: z.number().min(0).max(100),
    threshold: z.number().min(0).max(100),
    reason: z.string(),
  }),
  seniority_analysis: z.object({
    expected: z.string(),
    detected: z.string(),
    gap: z.string(),
    strength: z.string(),
  }),
  cv_tone: z.object({
    detected: z.enum(['passive', 'active', 'mixed']),
    examples: z.array(z.string()).max(5),
  }),
  audit: z.object({
    cv: z.object({
      score: z.number().min(0).max(100),
      issues: z.array(IssueHotSchema),
      // Backward compat — older analyses had strengths, new ones don't.
      strengths: z.array(z.string()).optional(),
    }),
    // See AnalyzeResponseSchema: sparse sources can come back as a bare string
    // from Claude — coerce to an empty audit instead of failing the analysis.
    github: z
      .object({
        score: z.number().min(0).max(100).nullable(),
        issues: z.array(IssueHotSchema),
        strengths: z.array(z.string()).optional(),
      })
      .catch({ score: null, issues: [], strengths: [] }),
    linkedin: z
      .object({
        score: z.number().min(0).max(100).nullable(),
        issues: z.array(IssueHotSchema),
        strengths: z.array(z.string()).optional(),
      })
      .catch({ score: null, issues: [], strengths: [] }),
    jd_match: AuditJdMatchSchema,
  }),
  hidden_red_flags: z.array(
    z.object({
      flag: z.string(),
      perception: z.string(),
    }),
  ),
  // Backward compat — older analyses had correlation, new ones don't.
  correlation: z
    .object({
      detected: z.boolean(),
      explanation: z.string(),
    })
    .optional(),
  job_details: JobDetailsSchema,
  /**
   * Required for NEW analyses (Claude's hot tool schema marks it required),
   * but kept optional here so we can replay mid-format DB rows where the
   * field was still stored under `deepAnalysis`. The merge helper handles
   * the fallback.
   */
  technical_analysis: TechnicalAnalysisSchema.optional(),
  challenge_analysis: ChallengeAnalysisSchema.optional(),
});

// =============================================================================
// DEEP pass schema — second response, indexed to the hot pass output.
// Fix arrays MUST have the same length as their hot counterparts.
// =============================================================================

export const DeepAnalyzeResponseSchema = z.object({
  /**
   * Kept optional for backward compatibility: analyses created before
   * `technical_analysis` was moved into the hot pass stored it in this
   * field. The merge helper falls back to it when the hot result lacks
   * the field. New analyses won't populate this.
   */
  technical_analysis: TechnicalAnalysisSchema.optional(),
  project_recommendation: ProjectRecommendationSchema.optional(),
  ats_critical_missing_keywords: z.array(AtsCriticalMissingKeywordSchema),
  // Verbatim highlight terms per source doc. Lives on the deep pass in the
  // split flow (the single-pass response carries it at the top level).
  highlight_terms: HighlightTermsSchema.optional(),
  fixes: z.object({
    seniority_analysis: FixSchema,
    // Optional — the tone diagnostic doesn't always need an actionable fix,
    // and we save ~300 tokens of output when Claude skips it.
    cv_tone: FixSchema.optional(),
    audit_cv_issues: z.array(FixSchema),
    audit_github_issues: z.array(FixSchema),
    audit_linkedin_issues: z.array(FixSchema),
    hidden_red_flags: z.array(FixSchema),
  }),
});

// =============================================================================
// Merged response — what the frontend ultimately consumes.
// Same shape as before the hot/deep split, for backward compatibility.
// =============================================================================

export const AnalyzeResponseSchema = z.object({
  score: z.number().min(0).max(100),
  verdict: z.enum(['Low', 'Medium', 'High']),
  confidence: z.object({
    score: z.number().min(0).max(100),
    reason: z.string(),
  }),
  breakdown: z.object({
    keyword_match: z.number().min(0).max(100),
    tech_stack_fit: z.number().min(0).max(100),
    experience_level: z.number().min(0).max(100),
    github_signal: z.number().min(0).max(100).nullable(),
    linkedin_signal: z.number().min(0).max(100).nullable(),
  }),
  ats_simulation: z.object({
    would_pass: z.boolean(),
    score: z.number().min(0).max(100),
    threshold: z.number().min(0).max(100),
    reason: z.string(),
    critical_missing_keywords: z.array(AtsCriticalMissingKeywordSchema).optional(),
  }),
  seniority_analysis: z.object({
    expected: z.string(),
    detected: z.string(),
    gap: z.string(),
    strength: z.string(),
    fix: FixSchema.optional(),
  }),
  cv_tone: z.object({
    detected: z.enum(['passive', 'active', 'mixed']),
    // Tool cap is 6 — keep one slot of headroom so an off-by-one from the
    // model never fails an expensive analysis.
    examples: z.array(z.string()).max(8),
    fix: FixSchema.optional(),
  }),
  audit: z.object({
    cv: z.object({
      score: z.number().min(0).max(100),
      issues: z.array(
        IssueHotSchema.extend({ fix: FixSchema.optional() }),
      ),
      strengths: z.array(z.string()).optional(),
    }),
    // github / linkedin are SPARSE sources: when the data is thin or absent,
    // Claude occasionally returns a bare string (e.g. "No GitHub profile to
    // audit") instead of the object. `.catch` coerces any malformed value to an
    // empty audit so a secondary field never fails the whole (expensive,
    // ~3 min) analysis. cv / jd_match stay strict — they're always present.
    github: z
      .object({
        score: z.number().min(0).max(100).nullable(),
        issues: z.array(
          IssueHotSchema.extend({ fix: FixSchema.optional() }),
        ),
        strengths: z.array(z.string()).optional(),
      })
      .catch({ score: null, issues: [], strengths: [] }),
    linkedin: z
      .object({
        score: z.number().min(0).max(100).nullable(),
        issues: z.array(
          IssueHotSchema.extend({ fix: FixSchema.optional() }),
        ),
        strengths: z.array(z.string()).optional(),
      })
      .catch({ score: null, issues: [], strengths: [] }),
    // P1: cover / motivation letter audit. Optional (absent on lean/owner
    // audits and on rows stored before P1); score is null when no letter.
    cover_letter: z
      .object({
        score: z.number().min(0).max(100).nullable(),
        issues: z.array(IssueHotSchema.extend({ fix: FixSchema.optional() })),
        strengths: z.array(z.string()).optional(),
      })
      .catch({ score: null, issues: [], strengths: [] })
      .optional(),
    jd_match: AuditJdMatchSchema,
  }),
  hidden_red_flags: z.array(
    z.object({
      flag: z.string(),
      perception: z.string(),
      fix: FixSchema.optional(),
    }),
  ),
  correlation: z
    .object({
      detected: z.boolean(),
      explanation: z.string(),
    })
    .optional(),
  job_details: JobDetailsSchema,
  project_recommendation: ProjectRecommendationSchema.optional(),
  challenge_analysis: ChallengeAnalysisSchema.optional(),
  technical_analysis: TechnicalAnalysisSchema.optional(),
  negotiation_analysis: NegotiationAnalysisSchema.nullable().optional(),
  /**
   * Pre-computed cross-profile inconsistencies from the user's ProfileDigest.
   * Surfaced in the analysis result so the frontend can render a dedicated
   * "Consistency check" section without re-fetching the digest.
   * Empty / undefined for anonymous users (no digest).
   */
  highlight_terms: HighlightTermsSchema.optional(),
  // Bullet-by-bullet review — optional so pre-densification DB rows replay.
  bullet_reviews: BulletReviewsSchema.optional(),
  // Set by the analysis shaper on redacted (free) payloads only.
  premium_locked: PremiumLockedSchema.optional(),
  cross_profile_inconsistencies: z
    .array(CrossProfileInconsistencySchema)
    .optional(),
  /**
   * Per-source chronology used by the Consistency tab timeline visualization.
   * Each entry is one job from one source — same job across multiple sources
   * appears multiple times (one per source) so the frontend can render parallel
   * bars and surface date divergences spatially.
   */
  timeline_entries: z.array(TimelineEntrySchema).optional(),
});

export class AnalyzeResponseDto extends createZodDto(AnalyzeResponseSchema) {}
export type AnalyzeResponse = z.infer<typeof AnalyzeResponseSchema>;
export type HotAnalyzeResponse = z.infer<typeof HotAnalyzeResponseSchema>;
export type DeepAnalyzeResponse = z.infer<typeof DeepAnalyzeResponseSchema>;
export type Issue = z.infer<typeof IssueSchema>;
export type IssueHot = z.infer<typeof IssueHotSchema>;
export type Fix = z.infer<typeof FixSchema>;

/**
 * Attach positional deep `fix` blocks onto their owning hot issues.
 *
 * The deep pass returns fixes as flat arrays that MUST be the same length and
 * order as the hot issues (enforced only by the prompt). If the model returns a
 * mismatched length, attaching by index would silently bind the WRONG fix to an
 * issue — the exact trust defect we must avoid. So on any length mismatch we
 * drop the fixes for that section (a missing fix degrades gracefully to a
 * skeleton; a wrong fix does not) and log a warning for observability.
 */
export function attachFixes<I, F>(
  issues: readonly I[],
  fixes: readonly F[] | undefined,
  label: string,
): (I & { fix: F | undefined })[] {
  if (!fixes) {
    return issues.map((issue) => ({ ...issue, fix: undefined }));
  }
  if (fixes.length !== issues.length) {
    // eslint-disable-next-line no-console
    console.warn(
      `[MERGE_ALIGN] ${label}: deep fixes length ${fixes.length} != hot issues length ${issues.length} — dropping fixes for this section to avoid misattachment`,
    );
    return issues.map((issue) => ({ ...issue, fix: undefined }));
  }
  return issues.map((issue, i) => ({ ...issue, fix: fixes[i] }));
}

/**
 * Merge hot pass + deep pass into the full AnalyzeResponse shape that the
 * frontend consumes. Re-injects `fix` blocks into their owners positionally,
 * guarding against length mismatches (see `attachFixes`).
 *
 * If `deep` is null/undefined, returns the hot result with deep fields absent
 * — the frontend handles missing deep fields with skeleton placeholders.
 */
export function mergeHotAndDeep(
  hot: HotAnalyzeResponse,
  deep: DeepAnalyzeResponse | null | undefined,
): AnalyzeResponse {
  // `cross_profile_inconsistencies` and `timeline_entries` aren't part of
  // HotAnalyzeResponseSchema — they're appended onto the result by
  // AnalyzeCvUseCase after this merge runs (sourced from the user's
  // ProfileDigest). When GetAnalysisUseCase re-runs this merge on a stored
  // row, the fields are present on the in-memory object even though the Zod
  // type doesn't list them. Preserve them through the merge so reloading an
  // analysis doesn't drop the Consistency tab data.
  const passthroughInconsistencies = (
    hot as unknown as { cross_profile_inconsistencies?: unknown }
  ).cross_profile_inconsistencies as
    | AnalyzeResponse['cross_profile_inconsistencies']
    | undefined;
  const passthroughTimeline = (
    hot as unknown as { timeline_entries?: unknown }
  ).timeline_entries as AnalyzeResponse['timeline_entries'] | undefined;

  const merged: AnalyzeResponse = {
    score: hot.score,
    verdict: hot.verdict,
    confidence: hot.confidence,
    breakdown: hot.breakdown,
    ats_simulation: {
      ...hot.ats_simulation,
      // Leave undefined when deep hasn't arrived — the frontend uses this to
      // distinguish "loading the keyword list" from "no missing keywords".
      critical_missing_keywords: deep?.ats_critical_missing_keywords,
    },
    seniority_analysis: {
      ...hot.seniority_analysis,
      fix: deep?.fixes.seniority_analysis,
    },
    cv_tone: {
      ...hot.cv_tone,
      fix: deep?.fixes.cv_tone,
    },
    audit: {
      cv: {
        ...hot.audit.cv,
        issues: attachFixes(
          hot.audit.cv.issues,
          deep?.fixes.audit_cv_issues,
          'audit_cv_issues',
        ),
      },
      github: {
        ...hot.audit.github,
        issues: attachFixes(
          hot.audit.github.issues,
          deep?.fixes.audit_github_issues,
          'audit_github_issues',
        ),
      },
      linkedin: {
        ...hot.audit.linkedin,
        issues: attachFixes(
          hot.audit.linkedin.issues,
          deep?.fixes.audit_linkedin_issues,
          'audit_linkedin_issues',
        ),
      },
      jd_match: hot.audit.jd_match,
    },
    hidden_red_flags: attachFixes(
      hot.hidden_red_flags,
      deep?.fixes.hidden_red_flags,
      'hidden_red_flags',
    ),
    // correlation is optional now — only present on legacy analyses.
    correlation: hot.correlation,
    job_details: hot.job_details,
    challenge_analysis: hot.challenge_analysis,
    project_recommendation: deep?.project_recommendation,
    // highlight_terms is generated by the deep pass in the split flow.
    highlight_terms: deep?.highlight_terms,
    // technical_analysis lives in the hot pass for new analyses; fall back to
    // deep for analyses created before the move (mid-format DB rows).
    technical_analysis: hot.technical_analysis ?? deep?.technical_analysis,
  };
  if (passthroughInconsistencies && passthroughInconsistencies.length > 0) {
    merged.cross_profile_inconsistencies = passthroughInconsistencies;
  }
  if (passthroughTimeline && passthroughTimeline.length > 0) {
    merged.timeline_entries = passthroughTimeline;
  }
  return merged;
}
