/**
 * Tool schema for ProfileDigest generation.
 *
 * Mirrors the structure of ProfileDigestSchema (Zod) in dto/profile-digest.dto.ts.
 * Generated by a Haiku 4.5 call once per user and refreshed when any source
 * (CV, LinkedIn, GitHub, portfolio) changes.
 *
 * Two design choices reflected here:
 *  - Verbatim sections (work_history, projects, tech_stack) get tight
 *    field-level descriptions so the model captures facts without paraphrasing.
 *  - Cross-profile inconsistencies have an explicit "be specific or skip"
 *    instruction — we'd rather have 0 items than vague ones.
 */

const SOURCE_ENUM = ['cv', 'linkedin', 'github', 'portfolio'] as const;

const WORK_HISTORY_ENTRY = {
  type: 'object' as const,
  properties: {
    company: { type: 'string' as const, description: 'Company name, verbatim.' },
    title: {
      type: 'string' as const,
      description: 'Job title as it appears in the source.',
    },
    start: {
      type: 'string' as const,
      description:
        "ISO yyyy-mm or 'present'. If only a year is given, use yyyy-01.",
    },
    end: {
      type: 'string' as const,
      description:
        "ISO yyyy-mm or 'present'. If only a year is given, use yyyy-12.",
    },
    location: {
      type: ['string', 'null'] as ['string', 'null'],
      description: 'City / remote / null if not stated.',
    },
    sources: {
      type: 'array' as const,
      items: { type: 'string' as const, enum: SOURCE_ENUM },
      minItems: 1,
      description:
        'Which source(s) confirmed this entry. If only one source mentions it, list only that one.',
    },
  },
  required: ['company', 'title', 'start', 'end', 'location', 'sources'],
};

const PROJECT_ENTRY = {
  type: 'object' as const,
  properties: {
    name: { type: 'string' as const },
    description: {
      type: 'string' as const,
      description: 'One-sentence summary of what the project does. ≤ 30 words.',
    },
    role_claimed: {
      type: 'string' as const,
      description:
        'Exact role the user claims: "Lead", "Solo dev", "Contributor", etc. Verbatim if stated, "Contributor" as fallback.',
    },
    dates: {
      type: ['string', 'null'] as ['string', 'null'],
      description:
        'Year or year range as written in source, or null if not stated.',
    },
    tech: {
      type: 'array' as const,
      items: { type: 'string' as const },
      maxItems: 10,
      description:
        'Up to 10 technologies / tools mentioned for this project, verbatim.',
    },
    outcomes: {
      type: 'array' as const,
      items: { type: 'string' as const },
      maxItems: 3,
      description:
        'Up to 3 outcomes / metrics if the source mentions them. Each ≤ 20 words. Empty array if none.',
    },
    link: {
      type: ['string', 'null'] as ['string', 'null'],
      description: 'URL (github, portfolio, live site) if stated, else null.',
    },
    sources: {
      type: 'array' as const,
      items: { type: 'string' as const, enum: SOURCE_ENUM },
      minItems: 1,
    },
  },
  required: [
    'name',
    'description',
    'role_claimed',
    'dates',
    'tech',
    'outcomes',
    'link',
    'sources',
  ],
};

const POSITIONING = {
  type: 'object' as const,
  properties: {
    headline: {
      type: 'string' as const,
      description:
        'One sentence summarizing how the user positions themselves across all sources. ≤ 20 words.',
    },
    tone: {
      type: 'array' as const,
      items: {
        type: 'string' as const,
        enum: [
          'confident',
          'reserved',
          'technical',
          'outcome-driven',
          'narrative',
          'minimal',
          'jargon-heavy',
        ],
      },
      minItems: 1,
      maxItems: 3,
      description: '1-3 tone categories that best describe the writing.',
    },
    polish_level: {
      type: 'string' as const,
      enum: ['low', 'medium', 'high'],
      description:
        'Overall perceived polish: spelling, structure, design quality of the supports.',
    },
  },
  required: ['headline', 'tone', 'polish_level'],
};

export const CROSS_PROFILE_INCONSISTENCY = {
  type: 'object' as const,
  properties: {
    severity: {
      type: 'string' as const,
      enum: ['critical', 'major', 'minor'],
      description:
        'critical = recruiter will reject on sight. major = recruiter will flag and ask. minor = small drift, mostly cosmetic.',
    },
    sources: {
      type: 'array' as const,
      items: { type: 'string' as const, enum: SOURCE_ENUM },
      minItems: 2,
      description: 'The 2+ sources where the divergence shows up.',
    },
    field: {
      type: 'string' as const,
      enum: [
        'job_title',
        'company',
        'dates',
        'tech_stack',
        'ownership',
        'seniority',
        'project_attribution',
        'location',
        'other',
      ],
    },
    description: {
      type: 'string' as const,
      description:
        'Plain-language description of the divergence, citing the actual values. ≤ 35 words.',
    },
    recruiter_perception: {
      type: 'string' as const,
      description:
        'How a senior recruiter is likely to read this. ≤ 25 words.',
    },
    anchor_date: {
      type: ['string', 'null'] as ['string', 'null'],
      description:
        "Representative yyyy-mm date for the divergence (used to position a marker on the chronology timeline). For a title mismatch: midpoint of the job. For a date discrepancy: the divergent month. For an ownership conflict: the project's start. NULL when the divergence isn't temporally locatable (e.g. tech_stack mismatch). Only use dates explicitly present in the sources — never invent.",
    },
  },
  required: [
    'severity',
    'sources',
    'field',
    'description',
    'recruiter_perception',
    'anchor_date',
  ],
};

export const TIMELINE_ENTRY = {
  type: 'object' as const,
  properties: {
    title: { type: 'string' as const, description: 'Job title verbatim from this source.' },
    company: { type: 'string' as const, description: 'Company name verbatim.' },
    source: { type: 'string' as const, enum: SOURCE_ENUM },
    start: {
      type: 'string' as const,
      description: 'ISO yyyy-mm. Use month 01 if only year is given.',
    },
    end: {
      type: 'string' as const,
      description: "ISO yyyy-mm or 'present'. Use month 12 if only year is given.",
    },
  },
  required: ['title', 'company', 'source', 'start', 'end'],
};

export const SUBMIT_PROFILE_DIGEST_TOOL = {
  name: 'submit_profile_digest',
  description:
    'Synthesize the candidate\'s full profile (CV + LinkedIn + GitHub + portfolio) into a single structured digest. Be ruthless on facts (verbatim where possible), conservative on qualitative signals (no embellishment), and SPECIFIC on cross-profile inconsistencies (cite exact divergent values — skip the entry rather than be vague).',
  input_schema: {
    type: 'object' as const,
    properties: {
      version: {
        type: 'number' as const,
        enum: [1],
        description: 'Schema version. Always 1 for this tool.',
      },
      work_history: {
        type: 'array' as const,
        items: WORK_HISTORY_ENTRY,
        maxItems: 12,
        description:
          'Chronological work history merged from all sources. Deduplicate by (company, title) — if CV and LinkedIn describe the same job with different dates, create ONE entry citing both sources and flag a cross_profile_inconsistency if the dates conflict.',
      },
      tech_stack: {
        type: 'array' as const,
        items: { type: 'string' as const },
        maxItems: 30,
        description:
          'Flat deduplicated list of all technologies / tools / frameworks visible across sources. Verbatim names.',
      },
      languages: {
        type: 'array' as const,
        items: { type: 'string' as const },
        maxItems: 10,
        description:
          'Spoken languages (not programming). Empty if none mentioned.',
      },
      projects: {
        type: 'array' as const,
        items: PROJECT_ENTRY,
        maxItems: 10,
        description:
          'Up to 10 projects merged from CV, GitHub, and portfolio. Deduplicate when the same project appears in multiple sources — cite all in `sources`.',
      },
      positioning: POSITIONING,
      signals: {
        type: 'array' as const,
        items: { type: 'string' as const },
        maxItems: 6,
        description:
          'Up to 6 short observed signals about the candidate. ≤ 15 words each. Examples: "ships polished work", "writes detailed case studies", "consistent 5+ year stints", "no design system experience visible".',
      },
      timeline_entries: {
        type: 'array' as const,
        items: TIMELINE_ENTRY,
        maxItems: 40,
        description:
          'Per-source chronology — ONE entry per source-occurrence of a job. If CV lists 5 jobs and LinkedIn lists 5 jobs with 4 overlapping, this array has ~9 entries (not 6). Use the dates EXACTLY as each source states them — do NOT reconcile, do NOT average. This powers the visual timeline that shows divergences as misaligned bars. Include every meaningful work entry from every available source; skip duplicates within the same source.',
      },
      cross_profile_inconsistencies: {
        type: 'array' as const,
        items: CROSS_PROFILE_INCONSISTENCY,
        maxItems: 8,
        description:
          'Concrete divergences between sources. Each entry MUST cite specific divergent values. If no real divergence exists, return an empty array — DO NOT pad with weak entries. A recruiter sees these in 30 seconds; vagueness here is worse than no entry. SKIP: date variances within ±2 months between sources for the same job, job-to-job gaps under 6 months, title translations across languages, minor title rephrasing within the same seniority. FLAG: real seniority/scope divergence, ownership contradictions, fabrications, durations off by >6 months.',
      },
      sources_available: {
        type: 'object' as const,
        properties: {
          cv: { type: 'boolean' as const },
          linkedin: { type: 'boolean' as const },
          github: { type: 'boolean' as const },
          portfolio: { type: 'boolean' as const },
        },
        required: ['cv', 'linkedin', 'github', 'portfolio'],
        description:
          'Which sources were available for this generation. Set false if a source was absent or empty.',
      },
    },
    required: [
      'version',
      'work_history',
      'tech_stack',
      'languages',
      'projects',
      'positioning',
      'signals',
      'timeline_entries',
      'cross_profile_inconsistencies',
      'sources_available',
    ],
  },
};

export const PROFILE_DIGEST_SYSTEM_PROMPT = `You are a profile synthesizer for RejectCheck. Your job is to produce a single structured digest of a candidate's professional identity by fusing whatever sources are provided (CV, LinkedIn, GitHub, portfolio).

Operating principles:
1. **Verbatim over paraphrase**: in work_history, projects, tech_stack, and timeline_entries, use the exact names and titles from the sources. Don't normalize "Sr." to "Senior" or invent acronyms.
2. **work_history is DEDUPLICATED, timeline_entries is NOT**: same job across CV and LinkedIn → ONE work_history entry with both sources cited. BUT the SAME job → TWO separate timeline_entries (one with source='cv' and CV's dates, one with source='linkedin' and LinkedIn's dates). The two fields serve different purposes — don't apply the same logic to both.
3. **timeline_entries dates are verbatim per source**: never reconcile or average. If CV says "09/2022 → 03/2023" and LinkedIn says "10/2022 → 02/2023", that's two entries with their own dates. The frontend renders parallel bars to make the divergence visible.
4. **Be specific on inconsistencies**: cite actual divergent values ("CV says 'Senior Designer 2022-2024' but LinkedIn says 'Lead Designer 2023-2024'"). Skip entries you can't make specific — empty array is fine.
5. **anchor_date is for visual placement**: each inconsistency gets a yyyy-mm date used to drop a marker on the timeline. For a title mismatch → midpoint of the disputed job. For a date discrepancy → the actually divergent month. For ownership conflicts → project start month. NULL only when truly not temporally locatable (e.g. tech_stack divergence with no time anchor). NEVER invent a date — use only dates explicitly stated in the sources.
6. **No embellishment in synthesized fields**: positioning.headline and signals describe what's observable, not what would sound impressive.
7. **Polish_level is harsh by default**: 'high' is reserved for truly polished supports (clean design, no typos, structured story). 'medium' for solid-but-typical. 'low' for visibly rushed or inconsistent.
8. **Recruiter mindset for cross_profile_inconsistencies**: write each \`recruiter_perception\` as how a senior recruiter would actually read it — practical, not academic.

**What is NOT an inconsistency (do NOT flag these):**
- **Date variances within ±2 months** for the same job between CV and LinkedIn (users round dates on LinkedIn — "Oct 2022" vs "Sept 2022" is normal noise, not a divergence).
- **Job-to-job gaps of less than 6 months**. Three months between two jobs is a normal job-search transition, not a red flag. Only flag if the gap is unexplained AND lasts more than 6 months.
- **Date "futures"** — never describe dates as "future" or "forecast" unless the source explicitly labels them so. If a date is past the current date, it's past. Period.
- **Translations** of the same job title across languages (e.g. "Software Engineer" EN vs "Ingénieur logiciel" FR) — these are equivalent, not divergent.
- **Title rephrasing within the same seniority** (e.g. "Full Stack Developer" vs "Full Stack Engineer") — minor naming variations are noise.
- **A CV that lists fewer, or only more recent, roles than LinkedIn.** A candidate cannot fit a 10+ year history on a one-page resume, so showing only the last few roles is normal length management, NOT an omission to flag and NOT an inconsistency. Only flag a role whose details are CONTRADICTED across sources, never one that is simply absent from the shorter document.

**What IS an inconsistency (do flag):**
- **Title with different seniority or scope**: "Senior" vs "Mid", "Lead" vs "Contributor", "Intern" vs full-time / staff role.
- **Different companies, different roles, or non-overlapping date ranges** for what should be the same job.
- **Ownership claims that contradict** (CV says "Led", portfolio says "Contributor"; one source says solo, another says team).
- **Tech stack claimed in one source, contradicted by visible evidence** in another (claims "React expert" but GitHub shows no React).
- **Job durations off by more than 6 months** between sources for the same role.

**Severity calibration:**
- **critical**: a recruiter rejects on sight (e.g. claims "Senior" with 1-year experience visible elsewhere, fabricated company, dates pretending to overlap impossibly).
- **major**: a recruiter flags and asks (e.g. clear title/seniority divergence, ownership ambiguity).
- **minor**: cosmetic drift (e.g. location stated in one source, omitted in another).

Output the digest via the submit_profile_digest tool. Return ONLY the tool call.`;
