import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Navbar } from '../../components/Navbar'
import {
  JsonLd,
  SITE_URL,
  articleSchema,
  breadcrumbSchema,
  faqPageSchema,
  softwareApplicationSchema,
} from '../../components/JsonLd'
import { hasLocale } from '../dictionaries'

const PAGE_PATH = '/cv-review'
const PUBLISHED_ISO = '2026-04-29'
const LAST_UPDATED_ISO = '2026-04-29'
const CANONICAL = `${SITE_URL}/en${PAGE_PATH}`

const TITLE = 'Deep CV Review for Developers — More Than a Score, a Real Diagnosis'
const DESCRIPTION =
  'Get a deep CV review tailored to a specific engineering role: tone audit, seniority signals, GitHub coherence, narrative consistency. Beyond a score — a full critique a hiring manager would write.'

type LangParams = { lang: string }

export async function generateMetadata({
  params,
}: {
  params: Promise<LangParams>
}): Promise<Metadata> {
  const { lang } = await params
  if (!hasLocale(lang) || lang !== 'en') return {}

  return {
    title: TITLE,
    description: DESCRIPTION,
    alternates: {
      canonical: CANONICAL,
      languages: {
        en: CANONICAL,
        'x-default': CANONICAL,
      },
    },
    openGraph: {
      title: TITLE,
      description: DESCRIPTION,
      url: CANONICAL,
      locale: 'en_US',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: TITLE,
      description: DESCRIPTION,
    },
  }
}

const FAQ_ITEMS = [
  {
    question: 'What is a CV review and how is it different from a CV check?',
    answer:
      'A check is binary and fast: did your CV match the keywords, did it pass parsing, what is the score. A review is qualitative: how does the narrative read, does the tone match the seniority you are claiming, does your GitHub back the story, are the bullets specific or vague. The output of a check is a number; the output of a review is feedback you can act on, line by line.',
  },
  {
    question: 'Is the review written in plain English or just structured scores?',
    answer:
      'Plain English. Each finding is phrased the way a senior hiring manager would write it in a one-on-one debrief: what stood out, what raised doubt, what to change first. Where useful, you get before/after rewrites of specific bullets — not just labels like "weak verb".',
  },
  {
    question: 'Does the review look at GitHub and LinkedIn?',
    answer:
      'Yes. The review treats your CV, GitHub, and LinkedIn as one application. Inconsistencies between them — title differences, claimed skills with no commit history, projects on the CV that no longer exist on GitHub — are flagged with the same weight a recruiter or hiring manager would give them.',
  },
  {
    question: 'How is the review tailored to a specific role?',
    answer:
      'You paste the target job description. The review is then anchored to that role: which of your bullets are relevant, which read off-target, where your seniority signaling matches the role level and where it slips. A generic review tells you what is wrong; a role-anchored review tells you what to fix for this specific opportunity.',
  },
  {
    question: 'How long does a deep review take?',
    answer:
      'Under 60 seconds. The review is generated by a dual-AI pipeline (GPT-4o and Claude) running in parallel — each model audits a different layer (narrative, technical signal, consistency, format), then the outputs are composed. Speed comes from concurrency, not from skipping depth.',
  },
  {
    question: 'Will the review rewrite my CV or just critique it?',
    answer:
      'The free deep review returns the critique with prioritized fixes and example rewrites for the highest-impact bullets. A full surgical rewrite (with all fixes applied and a clean PDF export) is a premium feature — but the diagnosis itself is free, and you can apply the fixes manually.',
  },
]

export default async function CvReviewPage({
  params,
}: {
  params: Promise<LangParams>
}) {
  const { lang } = await params
  if (!hasLocale(lang)) notFound()
  if (lang !== 'en') notFound()

  const breadcrumbs = breadcrumbSchema([
    { name: 'Home', url: `${SITE_URL}/en` },
    { name: 'CV Review', url: CANONICAL },
  ])

  const article = articleSchema({
    headline: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
    datePublished: PUBLISHED_ISO,
    dateModified: LAST_UPDATED_ISO,
    locale: 'en',
  })

  return (
    <>
      <JsonLd id="ld-breadcrumb-cv-review" data={breadcrumbs} />
      <JsonLd id="ld-faq-cv-review" data={faqPageSchema(FAQ_ITEMS)} />
      <JsonLd id="ld-article-cv-review" data={article} />
      <JsonLd id="ld-app-cv-review" data={softwareApplicationSchema('en')} />

      <div className="bg-rc-bg text-rc-text font-sans min-h-screen">
        <Navbar />

        {/* Hero */}
        <section className="max-w-[1100px] mx-auto px-5 md:px-[40px] pt-20 pb-16 md:pt-28 md:pb-20">
          <div className="flex items-center gap-3 mb-8">
            <div className="h-px w-6 bg-rc-red" />
            <span className="font-mono text-[10px] tracking-[0.22em] uppercase text-rc-red">
              Deep CV Review · For developers
            </span>
          </div>
          <h1 className="text-[40px] md:text-[58px] font-semibold leading-[1.08] tracking-[-0.025em] text-rc-text max-w-[860px] mb-6">
            Not a score.{' '}
            <span
              className="text-rc-red italic"
              style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
            >
              A real review
            </span>{' '}
            — the one a hiring manager would write.
          </h1>
          <p className="text-rc-muted text-[16px] md:text-[17px] leading-[1.7] max-w-[640px] mb-10">
            A score tells you something is broken. A review tells you what to change, line by
            line. Tone, seniority phrasing, narrative coherence, GitHub coherence — read like
            a debrief, not a checklist.
          </p>
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
            <Link
              href="/en/analyze"
              className="inline-flex items-center gap-2.5 bg-rc-red text-white font-mono text-[12px] tracking-[0.14em] uppercase px-7 py-3.5 rounded-xl hover:bg-[#b83332] transition-all duration-200 no-underline"
            >
              Get my CV reviewed free
              <svg width="12" height="12" viewBox="0 0 14 14" fill="none">
                <path
                  d="M2 7h10M7.5 3l4 4-4 4"
                  stroke="white"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
            <span className="font-mono text-[11px] text-rc-hint tracking-wide">
              Anchored to a specific role · Plain-English critique
            </span>
          </div>
        </section>

        {/* Score vs Review */}
        <section className="border-t-[0.5px] border-rc-border bg-rc-surface-hero">
          <div className="max-w-[1100px] mx-auto px-5 md:px-[40px] py-20 md:py-24">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-px w-6 bg-rc-border" />
              <span className="font-mono text-[10px] tracking-[0.22em] uppercase text-rc-hint">
                The difference
              </span>
            </div>
            <h2 className="text-[26px] md:text-[34px] font-semibold leading-[1.15] tracking-[-0.02em] text-rc-text mb-6 max-w-[700px]">
              An ATS score and a CV review answer different questions.
            </h2>
            <p className="text-rc-muted text-[15px] leading-[1.7] max-w-[700px] mb-10">
              Both are useful. They are not interchangeable. If you have already passed an ATS
              check and still keep getting silence, the gap is at the next layer — narrative
              and signaling — and a score will not surface it.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <div className="rounded-2xl border border-rc-border bg-rc-surface p-6">
                <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-rc-hint font-bold mb-3">
                  ATS / Resume score
                </p>
                <h3 className="text-[18px] font-semibold text-rc-text mb-3 leading-tight">
                  Did the machine pass me?
                </h3>
                <ul className="space-y-2 text-[14px] text-rc-muted leading-[1.7]">
                  <li>— Match percentage vs JD keywords</li>
                  <li>— Format and parsing flags</li>
                  <li>— Missing keywords with point values</li>
                  <li>— Output: a number + a fix list</li>
                </ul>
                <p className="mt-4 text-[13px] text-rc-hint">
                  Right tool when you want a quick pass/fail before submitting.{' '}
                  <Link
                    href="/en/resume-checker"
                    className="text-rc-red no-underline hover:underline font-medium"
                  >
                    Use the resume checker →
                  </Link>
                </p>
              </div>

              <div className="rounded-2xl border border-rc-red/30 bg-rc-red/5 p-6">
                <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-rc-red font-bold mb-3">
                  Deep CV review
                </p>
                <h3 className="text-[18px] font-semibold text-rc-text mb-3 leading-tight">
                  Why is this not landing interviews?
                </h3>
                <ul className="space-y-2 text-[14px] text-rc-muted leading-[1.7]">
                  <li>— Tone and seniority signaling per bullet</li>
                  <li>— Narrative coherence across sections</li>
                  <li>— GitHub vs CV vs LinkedIn cross-check</li>
                  <li>— Output: a written debrief + before/after rewrites</li>
                </ul>
                <p className="mt-4 text-[13px] text-rc-hint">
                  Right tool when the score is fine but you still get silence.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* What the review covers */}
        <section className="border-t-[0.5px] border-rc-border">
          <div className="max-w-[1100px] mx-auto px-5 md:px-[40px] py-20 md:py-24">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-px w-6 bg-rc-border" />
              <span className="font-mono text-[10px] tracking-[0.22em] uppercase text-rc-hint">
                What the review actually looks at
              </span>
            </div>
            <h2 className="text-[26px] md:text-[34px] font-semibold leading-[1.15] tracking-[-0.02em] text-rc-text mb-12 max-w-[680px]">
              Five lenses. Each one is what a different reader weighs.
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {[
                {
                  label: 'Tone — does this read at the right level?',
                  body:
                    'Active vs passive voice, ownership claims, level of abstraction. "Helped build" reads two levels below "owned and shipped". The review surfaces every bullet where the verb undersells the work.',
                },
                {
                  label: 'Narrative — does the story hold together?',
                  body:
                    'Job changes, promotions, tenure, gaps. Does the trajectory make sense? Are there silent reversals (senior title, then junior title) that need addressing? A coherent story reduces uncertainty for the reader.',
                },
                {
                  label: 'Signal — does GitHub back the CV?',
                  body:
                    'If your CV claims production-level Kubernetes, your GitHub should not show only React tutorials. The review cross-references commit history, language distribution, and project relevance against your stated stack.',
                },
                {
                  label: 'Positioning — are you the right candidate for this role?',
                  body:
                    'Anchored to the job description you provide. Where you are clearly aligned, where you over-pitch, where you under-pitch. Specific feedback per role, not a generic CV grade.',
                },
                {
                  label: 'Specificity — are bullets concrete?',
                  body:
                    'Generic bullets ("worked with cross-functional teams", "improved system performance") read as filler. The review flags vague claims and rewrites the worst offenders with concrete numbers and verbs.',
                },
                {
                  label: 'Consistency — CV ↔ LinkedIn ↔ GitHub',
                  body:
                    'Title differences, overlapping dates, claimed years of experience versus graduation year, recommendations that contradict the CV. Each inconsistency reduces trust by a measurable amount.',
                },
              ].map((f) => (
                <div
                  key={f.label}
                  className="rounded-2xl border border-rc-border bg-rc-surface p-6"
                >
                  <h3 className="text-[16px] font-semibold text-rc-text mb-2">{f.label}</h3>
                  <p className="text-[14px] text-rc-muted leading-[1.65]">{f.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Mid CTA */}
        <section className="border-t-[0.5px] border-rc-border bg-rc-surface-hero">
          <div className="max-w-[1100px] mx-auto px-5 md:px-[40px] py-16 md:py-20">
            <div className="rounded-2xl border border-rc-red/30 bg-rc-red/5 p-8 text-center">
              <h2 className="text-[22px] md:text-[28px] font-semibold tracking-[-0.02em] text-rc-text mb-4 max-w-[640px] mx-auto">
                Get the kind of feedback a senior would give over coffee.
              </h2>
              <p className="text-rc-muted text-[14px] mb-6 max-w-[520px] mx-auto">
                Anchored to a real role. Plain-English critique. Before/after rewrites for the
                bullets that need it most.
              </p>
              <Link
                href="/en/analyze"
                className="inline-flex items-center gap-2 bg-rc-red text-white font-mono text-[12px] tracking-[0.14em] uppercase px-7 py-3 rounded-xl hover:bg-[#b83332] transition-all duration-200 no-underline"
              >
                Run free deep review →
              </Link>
            </div>
          </div>
        </section>

        {/* What you get back */}
        <section className="border-t-[0.5px] border-rc-border">
          <div className="max-w-[1100px] mx-auto px-5 md:px-[40px] py-20 md:py-24">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-px w-6 bg-rc-border" />
              <span className="font-mono text-[10px] tracking-[0.22em] uppercase text-rc-hint">
                What you get back
              </span>
            </div>
            <h2 className="text-[26px] md:text-[34px] font-semibold leading-[1.15] tracking-[-0.02em] text-rc-text mb-12 max-w-[640px]">
              A review that reads like a real debrief.
            </h2>

            <div className="space-y-5">
              {[
                {
                  n: '01',
                  title: 'A written critique, not a checklist',
                  body:
                    'Top 5-7 findings expressed in plain English: what stood out, what raised doubt, what would land differently with the hiring manager. Each finding is anchored to a specific section or bullet of your CV.',
                },
                {
                  n: '02',
                  title: 'Before / after rewrites for high-impact bullets',
                  body:
                    'For the 3-5 weakest bullets, you get a concrete suggested rewrite — same content, stronger phrasing. Side-by-side so you can see what changed and why.',
                },
                {
                  n: '03',
                  title: 'Priority-ordered fix list',
                  body:
                    'Every finding ranked by impact on this specific role. Apply the top 3 first. This is not a 40-item generic checklist — it is the few changes that actually move the application.',
                },
                {
                  n: '04',
                  title: 'Cross-application coherence call-out',
                  body:
                    'If your GitHub or LinkedIn weakens or contradicts the CV story, you get a clear, named flag — with the exact item that triggers it. Most candidates never see these because they only review the CV in isolation.',
                },
              ].map((s) => (
                <div
                  key={s.n}
                  className="rounded-2xl border border-rc-border bg-rc-surface p-6"
                >
                  <div className="flex items-baseline gap-3 mb-2">
                    <span className="font-mono text-[11px] text-rc-red tracking-[0.16em]">
                      {s.n}
                    </span>
                    <h3 className="text-[18px] font-semibold text-rc-text leading-tight">
                      {s.title}
                    </h3>
                  </div>
                  <p className="text-[14px] text-rc-muted leading-[1.7] pl-[40px]">
                    {s.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="border-t-[0.5px] border-rc-border bg-rc-bg">
          <div className="max-w-[900px] mx-auto px-5 md:px-[40px] py-20 md:py-24">
            <div className="flex items-center gap-3 mb-6">
              <div className="h-px w-6 bg-rc-red" />
              <span className="font-mono text-[10px] tracking-[0.22em] uppercase text-rc-red">
                FAQ
              </span>
            </div>
            <h2 className="text-[26px] md:text-[34px] font-semibold leading-[1.15] tracking-[-0.02em] text-rc-text mb-10">
              Deep CV review — what developers ask
            </h2>
            <div className="space-y-3">
              {FAQ_ITEMS.map((item) => (
                <details
                  key={item.question}
                  className="group rounded-xl border border-rc-border bg-rc-surface"
                >
                  <summary className="cursor-pointer list-none flex items-start justify-between gap-4 px-5 py-4 md:px-6 md:py-5">
                    <h3 className="text-[16px] md:text-[17px] font-semibold text-rc-text leading-[1.35]">
                      {item.question}
                    </h3>
                    <span
                      aria-hidden="true"
                      className="shrink-0 mt-1 font-mono text-[18px] text-rc-red transition-transform group-open:rotate-45 select-none"
                    >
                      +
                    </span>
                  </summary>
                  <div className="px-5 pb-5 md:px-6 md:pb-6 -mt-1">
                    <p className="text-rc-muted text-[14px] md:text-[15px] leading-[1.7]">
                      {item.answer}
                    </p>
                  </div>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="border-t-[0.5px] border-rc-border bg-rc-surface">
          <div className="max-w-[1100px] mx-auto px-5 md:px-[40px] py-20 md:py-24 text-center">
            <h2 className="text-[28px] md:text-[40px] font-semibold leading-[1.12] tracking-[-0.025em] text-rc-text mb-6 max-w-[700px] mx-auto">
              Stop guessing why your CV is not landing. Get the critique.
            </h2>
            <p className="font-mono text-[12px] md:text-[13px] tracking-[0.06em] text-rc-hint mb-8">
              Anchored to one role. Plain-English. Before/after rewrites included.
            </p>
            <Link
              href="/en/analyze"
              className="inline-flex items-center gap-2.5 bg-rc-red text-white font-mono text-[12px] tracking-[0.14em] uppercase px-8 py-4 rounded-xl hover:bg-[#b83332] transition-all duration-200 no-underline"
            >
              Get my CV reviewed free
              <svg width="12" height="12" viewBox="0 0 14 14" fill="none">
                <path
                  d="M2 7h10M7.5 3l4 4-4 4"
                  stroke="white"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
          </div>
        </section>

        <footer className="border-t-[0.5px] border-rc-border py-6 px-5 md:px-[40px] flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="font-mono text-[13px] text-rc-muted">
            © RejectCheck — Built for developers
          </div>
          <div className="flex gap-6 flex-wrap justify-center">
            <Link
              href="/en/software-engineer-cv"
              className="font-mono text-[11px] tracking-[0.05em] text-rc-muted no-underline hover:text-rc-text"
            >
              SE CV Guide
            </Link>
            <Link
              href="/en/resume-checker"
              className="font-mono text-[11px] tracking-[0.05em] text-rc-muted no-underline hover:text-rc-text"
            >
              Resume Checker
            </Link>
            <Link
              href="/en/ats-checker"
              className="font-mono text-[11px] tracking-[0.05em] text-rc-muted no-underline hover:text-rc-text"
            >
              ATS Checker
            </Link>
            <Link
              href="/en/pricing"
              className="font-mono text-[11px] tracking-[0.05em] text-rc-muted no-underline hover:text-rc-text"
            >
              Pricing
            </Link>
            <Link
              href="/en/privacy"
              className="font-mono text-[11px] tracking-[0.05em] text-rc-muted no-underline hover:text-rc-text"
            >
              Privacy (GDPR)
            </Link>
          </div>
        </footer>
      </div>
    </>
  )
}
