/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze a CV against a job description */
        post: operations["AnalyzeController_analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get analysis history for a user */
        get: operations["AnalyzeController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: operations["AnalyzeController_getProfile"];
        put?: never;
        /** Update user profile */
        post: operations["AnalyzeController_updateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific analysis by ID */
        get: operations["AnalyzeController_getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete an analysis */
        post: operations["AnalyzeController_deleteAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeController_createCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StripeController_getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WaitlistController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeRequestDto: {
            jobDescription: string;
            githubUsername?: string;
            motivationLetterText?: string;
            /** Format: email */
            email?: string;
            isRegistered?: boolean;
        };
        AnalyzeResponseDto: {
            score: number;
            /** @enum {string} */
            verdict: "Low" | "Medium" | "High";
            confidence: {
                score: number;
                reason: string;
            };
            breakdown: {
                keyword_match: number;
                tech_stack_fit: number;
                experience_level: number;
                github_signal: number | null;
                linkedin_signal: number | null;
            };
            ats_simulation: {
                would_pass: boolean;
                score: number;
                threshold: number;
                reason: string;
                critical_missing_keywords: {
                    keyword: string;
                    jd_frequency: number;
                    required: boolean;
                    sections_missing: string[];
                    score_impact: number;
                }[];
            };
            seniority_analysis: {
                expected: string;
                detected: string;
                gap: string;
                strength: string;
                fix: {
                    summary: string;
                    steps: string[];
                    example: {
                        before: string;
                        after: string;
                    } | null;
                    project_idea: {
                        name: string;
                        description: string;
                        endpoints: string[];
                        bonus: string | null;
                        proves: string;
                    } | null;
                    time_required: string;
                };
            };
            cv_tone: {
                /** @enum {string} */
                detected: "passive" | "active" | "mixed";
                examples: string[];
                fix: {
                    summary: string;
                    steps: string[];
                    example: {
                        before: string;
                        after: string;
                    } | null;
                    project_idea: {
                        name: string;
                        description: string;
                        endpoints: string[];
                        bonus: string | null;
                        proves: string;
                    } | null;
                    time_required: string;
                };
            };
            audit: {
                cv: {
                    score: number;
                    issues: {
                        /** @enum {string} */
                        severity: "critical" | "major" | "minor";
                        /** @enum {string} */
                        category: "keywords" | "impact" | "seniority" | "stack" | "format" | "tone" | "consistency";
                        what: string;
                        why: string;
                        fix: {
                            summary: string;
                            steps: string[];
                            example: {
                                before: string;
                                after: string;
                            } | null;
                            project_idea: {
                                name: string;
                                description: string;
                                endpoints: string[];
                                bonus: string | null;
                                proves: string;
                            } | null;
                            time_required: string;
                        };
                    }[];
                    strengths: string[];
                };
                github: {
                    score: number | null;
                    issues: {
                        /** @enum {string} */
                        severity: "critical" | "major" | "minor";
                        /** @enum {string} */
                        category: "keywords" | "impact" | "seniority" | "stack" | "format" | "tone" | "consistency";
                        what: string;
                        why: string;
                        fix: {
                            summary: string;
                            steps: string[];
                            example: {
                                before: string;
                                after: string;
                            } | null;
                            project_idea: {
                                name: string;
                                description: string;
                                endpoints: string[];
                                bonus: string | null;
                                proves: string;
                            } | null;
                            time_required: string;
                        };
                    }[];
                    strengths: string[];
                };
                linkedin: {
                    score: number | null;
                    issues: {
                        /** @enum {string} */
                        severity: "critical" | "major" | "minor";
                        /** @enum {string} */
                        category: "keywords" | "impact" | "seniority" | "stack" | "format" | "tone" | "consistency";
                        what: string;
                        why: string;
                        fix: {
                            summary: string;
                            steps: string[];
                            example: {
                                before: string;
                                after: string;
                            } | null;
                            project_idea: {
                                name: string;
                                description: string;
                                endpoints: string[];
                                bonus: string | null;
                                proves: string;
                            } | null;
                            time_required: string;
                        };
                    }[];
                    strengths: string[];
                };
                jd_match: {
                    required_skills: {
                        skill: string;
                        found: boolean;
                        evidence: string | null;
                    }[];
                    experience_gap: string | null;
                };
            };
            hidden_red_flags: {
                flag: string;
                perception: string;
                fix: {
                    summary: string;
                    steps: string[];
                    example: {
                        before: string;
                        after: string;
                    } | null;
                    project_idea: {
                        name: string;
                        description: string;
                        endpoints: string[];
                        bonus: string | null;
                        proves: string;
                    } | null;
                    time_required: string;
                };
            }[];
            correlation: {
                detected: boolean;
                explanation: string;
            };
            job_details: {
                title: string;
                company: string;
            };
            project_recommendation: {
                name: string;
                description: string;
                technologies: string[];
                key_features: string[];
                why_it_matters: string;
                what_matters: string[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyzeController_analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AnalyzeRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponseDto"];
                };
            };
        };
    };
    AnalyzeController_getHistory: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponseDto"][];
                };
            };
        };
    };
    AnalyzeController_getProfile: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyzeController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyzeController_getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponseDto"];
                };
            };
        };
    };
    AnalyzeController_deleteAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_createCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_getSubscription: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_handleWebhook: {
        parameters: {
            query?: never;
            header: {
                "stripe-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WaitlistController_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
